contentdir = "content"
theme = "hugo-base-theme"
languageCode = "en-us"
title = "Choria"
googleAnalytics = "UA-10152852-12"

[params]
    mainIcon = "/img/choria-vert-400px.png"

[[params.social]]
    title = "docs"
    url = "docs/about/"
    button = "primary"
[[params.social]]
    title = "github"
    url = "https://github.com/ripienaar/mcollective-choria/"
    button = "success"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/ripienaar"
    button = "info"
