baseurl = "http://dev1.devco.net:9292"
contentdir = "content"
theme = "hugo-theme-learn"
title = "Choria Orchestrator"
googleAnalytics = "UA-10152852-12"

[markup.goldmark.renderer]
  unsafe= true

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  description = "Documentation for the Choria Orchestrator"
  author = "R.I.Pienaar <rip@devco.net>"
  showVisitedLinks = false
  menu = [ "about", "concepts", "tasks", "playbooks", "scout", "autoagents", "federation", "adapters", "development", "deployment", "configuration" ]
  themeVariant = "choria"
